### ISSUE TITLE
Attribute 'self.socket_path' doesn't exist

### ISSUE THREAD

**Issue by alpargatagazer** [mtreinish/pycmus#1]
I was reading the code in order to use for my own project and then my IDE noticed a problem with the program.
In:
```Python
def _get_cmus_conf_dir(self)
```
you use *self.socket_path*, which it's not possible since there is no such attribute in the class.
A fine solution might be just adding a new parameter called *socket_path* on the method. So, basically the method that calls the function I'm talking about and that one will be something like:
```Python
def _get_socket_path(self, socket_path=None):
        if "CMUS_SOCKET" in os.environ:
            return os.environ["CMUS_SOCKET"]
        else:
            if "XDG_RUNTIME_DIR" in os.environ:
                return os.path.join(os.environ["XDG_RUNTIME_DIR"],
                                    "cmus-socket")
            else:
                conf_dir = self._get_cmus_conf_dir(socket_path)
                return os.path.join(conf_dir, 'socket')

def _get_cmus_conf_dir(self, socket_path=None):
        if socket_path:
            return socket_path
```

**Comment by mtreinish** [comment]
Yep, that's a good catch. Feel free to push up a PR for the fix. _get_cmus_conf_dir() should take the socket_path variable in as a parameter instead of relying on an instance variable.

**Comment by mtreinish** [comment]
We probably shouldn't close this until the fix is merged
